from sqlalchemy import (
    Column, String, Text, Boolean, DateTime, Float,
    ForeignKey, JSON, Enum as SAEnum
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
import uuid
import enum

from app.core.database import Base


class FIRStatus(str, enum.Enum):
    PENDING = "pending"
    INDEXED = "indexed"
    ANALYSED = "analysed"
    CLOSED = "closed"


class RiskLevel(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class FIR(Base):
    __tablename__ = "firs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    case_number = Column(String(50), unique=True, nullable=False, index=True)
    district = Column(String(50), nullable=False)
    police_station = Column(String(100), nullable=False)
    date_of_incident = Column(DateTime(timezone=True), nullable=True)
    date_registered = Column(DateTime(timezone=True), server_default=func.now())
    
    # Raw content
    raw_text = Column(Text, nullable=False)
    original_language = Column(String(10), default="en")  # "en" or "ml"
    
    # NLP-extracted entities (JSON)
    extracted_entities = Column(JSON, default=dict)
    # e.g. {"complainant": "...", "accused": [...], "location": "...", "weapon": "...", "property": "..."}
    
    # IPC/legal classification
    ipc_sections = Column(JSON, default=list)
    # e.g. [{"section": "379", "title": "Theft", "description": "...", "confidence": 0.92}]
    
    crime_category = Column(String(100), nullable=True)
    risk_level = Column(SAEnum(RiskLevel), default=RiskLevel.MEDIUM, nullable=False)
    
    # MO pattern
    mo_pattern = Column(String(200), nullable=True)
    mo_cluster_id = Column(String(50), nullable=True)
    
    # Embedding
    status = Column(SAEnum(FIRStatus), default=FIRStatus.PENDING, nullable=False)
    embedding_id = Column(String(100), nullable=True)  # ChromaDB doc ID
    indexed_at = Column(DateTime(timezone=True), nullable=True)
    
    # Summary generated by AI
    ai_summary = Column(Text, nullable=True)
    
    # Geolocation
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    
    # Relations
    officer_id = Column(UUID(as_uuid=True), ForeignKey("officers.id"), nullable=True)
    officer = relationship("Officer", back_populates="firs")
    case = relationship("Case", back_populates="fir", uselist=False, lazy="select")
